LOAD DATA LOCAL INFILE './RES/SYSTEM_USER.CSV' 
INTO TABLE SYSTEM_USER
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\N'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE './RES/CLINIC.CSV' 
INTO TABLE CLINIC
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\N'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE './RES/DIAGNOSIS_ROOM.CSV' 
INTO TABLE DIAGNOSIS_ROOM
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\N'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE './RES/PATIENT.CSV' 
INTO TABLE PATIENT
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\N'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE './RES/DOCTOR.CSV' 
INTO TABLE DOCTOR
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\N'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE './RES/PHARMACIST.CSV' 
INTO TABLE PHARMACIST
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\N'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE './RES/SCHEDULE.CSV' 
INTO TABLE SCHEDULE
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\N'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE './RES/DIAGNOSIS.CSV' 
INTO TABLE DIAGNOSIS
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\N'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE './RES/DISEASE.CSV' 
INTO TABLE DISEASE
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\N'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE './RES/MEDICINE.CSV' 
INTO TABLE MEDICINE
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\N'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE './RES/RECEIPT.CSV' 
INTO TABLE RECEIPT
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\N'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE './RES/DISPENSATION.CSV' 
INTO TABLE DISPENSATION
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\N'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE './RES/SUPPLIER.CSV' 
INTO TABLE SUPPLIER
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\N'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE './RES/PHARMA_ROOM.CSV' 
INTO TABLE PHARMA_ROOM
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\N'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE './RES/MEDICINE_ORDER.CSV' 
INTO TABLE MEDICINE_ORDER
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\N'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE './RES/STORED_MEDICINE.CSV' 
INTO TABLE STORED_MEDICINE
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\N'
IGNORE 1 ROWS;