DELIMITER $$
CREATE TRIGGER receiptLog
BEFORE UPDATE ON RECEIPT
FOR EACH ROW
BEGIN
	INSERT INTO RECEIPT_LOG VALUES (OLD.receipt_number, NOW());
END $$

CREATE TRIGGER orderLog
BEFORE UPDATE ON MEDICINE_ORDER
FOR EACH ROW
BEGIN
	INSERT INTO ORDER_LOG VALUES (OLD.order_id, NOW());
END $$
DELIMITER ;

